export JVM_OPTS=-Xmx1g 
export NUM_THREADS=1
export SAMTOOLS_SORT_MEM=1G
export GENOME=hg19
export GMAPDB=/path/to/gmapdb
export GTF=/path/to/refGene.sorted.gtf.gz
export TRANSCRIPTS_FASTA=/path/to/refGene.fa
export GENOME_FASTA=/path/to/hg19.fa
export RNABLOOM_PARAMS='-ntcard -fpr 0.005 -chimera -extend -tiplength 5'
