#!/bin/sh
# Exec script with awk. Don't remove slash \
exec awk -f "$0" "$@"

!/^>/ { next }
{ getline seq }
length(seq) >= min { print $0 "\n" seq }

#Code from: http://bioinfofly.wordpress.com/2012/07/09/binawk-f-nex/

