#!/bin/bash
set -euo pipefail

script_dir=`dirname $0`
script_name=`basename $0`

version=$(python $script_dir/find_sv.py --version)

function usage {
	echo Program: $script_name
	echo Version: $version
	echo
	echo "Usage: $script_name <sample> [options]" 
	echo
	echo "sample:	genome		find structural variants"
	echo "	transcriptome	find gene fusions, indels, PTDs, ITDs, novel splice variants"
}

if [ $# -gt 0 ]
then
	sample=$1
	shift
else
	usage
	exit 1
fi

if [ $sample = "transcriptome" ]
then
	if [ $# -gt 0 ]
	then
		python $script_dir/map_transcripts.py $@
	else
		msg=$(python $script_dir/map_transcripts.py --help)
		echo "$msg" | sed 's/map_transcripts.py/pavfinder transcriptome/'
	fi
elif [ $sample = "genome" ]
then
	if [ $# -gt 0 ]
	then
		python $script_dir/find_sv.py $@
	else
		msg=$(python $script_dir/find_sv.py --help)
		echo "$msg" | sed 's/find_sv.py/pavfinder genome/'
	fi
else
	usage
fi

